function k(b,a,c,d){b.v.Eb(b.ib,a,c,d,void 0)}function l(b,a,c,d){b.v.ca?k(b,a,c,d):b.v.ve()._OnMessageFromDOM({type:"event",component:b.ib,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function p(b,a,c){b.v.C(b.ib,a,c)}function aa(b,a){for(const [c,d]of a)p(b,c,d)}function t(b){b.Pb||(b.v.gd(b.Od),b.Pb=!0)}window.Cb=class{constructor(b,a){this.v=b;this.ib=a;this.Pb=!1;this.Od=()=>this.Ka()}Yc(){}Ka(){}};
window.cf=class{constructor(){this.Vc=-1}j(){-1!==this.Vc&&(self.clearTimeout(this.Vc),this.Vc=-1)}};"use strict";class ba{constructor(b){this.Dc=b;this.Gc=!1;this.Nc=!0}}function ca(b,a){const c=a.elementId,d=b.bd(c,a),e=new ba(d);b.lb.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Nc=!!a.isVisible;d.addEventListener("focus",()=>{u(b,"elem-focused",c)});d.addEventListener("blur",()=>{u(b,"elem-blurred",c)});b.Lb&&document.body.appendChild(d)}
function v(b,a,c){p(b,a,d=>{const e=w(b,d.elementId);return c(e,d)})}function w(b,a){b=b.lb.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Dc}function u(b,a,c,d){d||(d={});d.elementId=c;k(b,a,d)}
window.ge=class extends self.Cb{constructor(b){super(b,"file-chooser");this.lb=new Map;this.Lb=!0;aa(this,[["create",a=>ca(this,a)],["destroy",a=>{a=a.elementId;const c=w(this,a);this.Lb&&c.parentElement.removeChild(c);this.lb.delete(a)}],["set-visible",a=>{if(this.Lb){var c=this.lb.get(a.elementId),d=c.Dc;c.Gc?d.style.display=a.isVisible?"":"none":c.Nc=!!a.isVisible}}],["update-position",a=>{if(this.Lb){var c=this.lb.get(a.elementId),d=c.Dc;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=
a.width+"px";d.style.height=a.height+"px";a=a.fontSize;null!==a&&(d.style.fontSize=a+"em");c.Gc||(c.Gc=!0,c.Nc&&(d.style.display=""))}}],["update-state",a=>{const c=w(this,a.elementId);this.rc(c,a)}],["focus",a=>{const c=w(this,a.elementId);a.focus?c.focus():c.blur()}],["set-css-style",a=>{const c=w(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",a=>{w(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{w(this,a.elementId).removeAttribute(a.name)}]]);
v(this,"get-element",a=>a)}bd(){throw Error("required override");}rc(){throw Error("required override");}};"use strict";const da=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent),ea=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let fa=0;
function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Te?new Promise(c=>{const d="c3_resolve_"+fa;++fa;self[d]=c;a.textContent=b.Xe+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ha=!1,ia=!1;function ja(){if(!ha){try{new Worker("blob://",{get type(){ia=!0}})}catch(b){}ha=!0}return ia}let C=new Audio;
const ka={"audio/webm; codecs=opus":!!C.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!C.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!C.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!C.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!C.canPlayType("audio/mp4"),"audio/mpeg":!!C.canPlayType("audio/mpeg")};C=null;async function la(b){b=await ma(b);return(new TextDecoder("utf-8")).decode(b)}
function ma(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const E=[];let F=0;window.RealFile=window.File;const G=[],pa=new Map,qa=new Map;let ra=0;const sa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");sa.push(b)};const ta=new Set(["cordova","playable-ad","instant-games"]);let ua=!1;
window.fb=class b{constructor(a){this.ca=a.Ze;this.va=null;this.ba="";this.Xa=a.We;this.zb={};this.Qa=this.ta=null;this.Nb=[];this.J=this.wa=null;this.Kc=!1;this.vd=0;this.ob=null;this.Wa=-1;this.Oe=()=>this.Ce();this.Va=[];this.B=a.Pd;this.Qb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ja()||(this.ca=!1);this.ca&&ea&&(this.ca=!1);if("playable-ad"===this.B||"instant-games"===this.B)this.ca=!1;if("cordova"===this.B&&this.ca)if(y){const c=
/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.Tb=this.qa=null;"html5"!==this.B||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",c=>this.ye(c));this.C("runtime","create-job-worker",()=>this.ze());"cordova"===this.B?document.addEventListener("deviceready",
()=>this.kd(a)):this.kd(a)}j(){this.sc();this.va&&(this.va=this.va.onmessage=null);this.ta&&(this.ta.terminate(),this.ta=null);this.Qa&&(this.Qa.j(),this.Qa=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}ke(){return da&&"cordova"===this.B}nc(){const a=navigator.userAgent;return da&&ta.has(this.B)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}ie(){return y}dd(){return y&&ta.has(this.B)}async kd(a){"macos-wkwebview"===this.B&&this.He();if("playable-ad"===this.B){this.qa=
self.c3_base64files;this.Tb={};await this.re();for(let d=0,e=a.Za.length;d<e;++d){var c=a.Za[d];this.Tb.hasOwnProperty(c)?a.Za[d]={Te:!0,Xe:this.Tb[c]}:this.qa.hasOwnProperty(c)&&(a.Za[d]=URL.createObjectURL(this.qa[c]))}a.fc=[]}if("nwjs"===this.B&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.gd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Ve?this.ba=a.Ve:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=
this.ba.substr(0,c+1)));a.af&&(this.zb=a.af);c=new MessageChannel;this.va=c.port1;this.va.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Be(d));this.ob=new self.le(this);await va(this.ob);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.ca?await this.xe(a,c.port2):await this.we(a,c.port2)}uc(a){a=this.zb.hasOwnProperty(a)?this.zb[a]:a.endsWith("/workermain.js")&&this.zb.hasOwnProperty("workermain.js")?this.zb["workermain.js"]:"playable-ad"===this.B&&this.qa.hasOwnProperty(a)?this.qa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ic(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.B&&this.Qb)return a=await this.Bb(d.Se?a:this.Xa+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}oa(){return Math.max(window.innerWidth,1)}ia(){return Math.max(window.innerHeight,1)}jd(a){var c=this.ba,d=location.href,e=this.oa(),f=this.ia(),g=window.devicePixelRatio,h=b.cb(),m=a.gf,q=window.cr_previewImageBlobs||this.qa,n=window.cr_previewProjectFileBlobs,A=window.cr_previewProjectFiles,x=window.ef||
"";a=a.Pd;var r=(new URLSearchParams(self.location.search)).has("debug"),B=this.ob;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:m,previewImageBlobs:q,previewProjectFileBlobs:n,previewProjectFileSWUrls:A,swClientId:x,exportType:a,isDebug:r,ife:!!self.ff,jobScheduler:{inputPort:B.Jc,outputPort:B.Rc,maxNumWorkers:B.Le},supportedAudioFormats:ka,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Xa+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.Xa+"opus.wasm.wasm",isFileProtocol:this.Qb,isiOSCordova:this.ke(),isiOSWebView:this.nc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async xe(a,c){const d=this.uc(a.$e);"preview"===this.B?(this.ta=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,m)=>{const q=n=>{this.ta.removeEventListener("message",q);n.data&&"ok"===n.data.type?h():m()};this.ta.addEventListener("message",q);this.ta.postMessage({type:"construct-worker-init","import":(new URL(d,
this.ba)).toString()})})):this.ta=await this.ic(d,this.ba,{type:"module",name:"Runtime",Se:!0});this.J=document.createElement("canvas");this.J.style.display="none";const e=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.fc||[],g=a.Za;f=await Promise.all(f.map(h=>this.La(h)));g=await Promise.all(g.map(h=>this.La(h)));if("cordova"===this.B)for(let h=0,m=a.ec.length;h<m;++h){const q=
a.ec[h],n=q[0];if(n===a.Wc||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))q[1]=await this.La(n)}this.ta.postMessage(Object.assign(this.jd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.ec,mainProjectScript:a.Wc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...wa(this.ob)]);this.Nb=G.map(h=>new h(this));this.hd();xa(this.wa);self.c3_callFunction=(h,m)=>{var q=this.wa;return q.v.fd(q.ib,"js-invoke-function",
{name:h,params:m},void 0,void 0)};"preview"===this.B&&(self.goToLastErrorScript=()=>this.Eb("runtime","go-to-last-error-script"))}async we(a,c){this.J=document.createElement("canvas");this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Nb=G.map(g=>new g(this));this.hd();var d=a.Za.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);Array.isArray(a.fc)&&d.unshift(...a.fc);d=await Promise.all(d.map(g=>
this.La(g)));await Promise.all(d.map(g=>z(g)));d=self.C3_ProjectScriptsStatus;const e=a.Wc,f=a.ec;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.La(h),await z(h),"preview"!==this.B||d[g]||this.md(g,"main script did not run to completion")}catch(m){this.md(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.La(h),await z(h);"preview"===this.B&&"object"!==typeof self.bf.df?(this.Ib(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.jd(a),{isInWorker:!1,messagePort:c,canvas:this.J,runOnStartupFunctions:sa}),xa(this.wa),this.ld(),this.Qa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Qa,a))}md(a,c){this.Ib();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}ld(){this.Ib()}Ib(){const a=
window.Qe;a&&(a.parentElement.removeChild(a),window.Qe=null)}async ze(){const a=await ya(this.ob);return{outputPort:a,transferables:[a]}}ve(){if(this.ca)throw Error("not available in worker mode");return this.Qa}Eb(a,c,d,e,f){this.va.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}fd(a,c,d,e,f){const g=ra++,h=new Promise((m,q)=>{qa.set(g,{resolve:m,reject:q})});this.va.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Ae(a);if("result"===c)this.De(a);else if("runtime-ready"===c)this.Ee();else if("alert-error"===c)this.Ib(),alert(a.message);else if("creating-runtime"===c)this.ld();else throw Error(`unknown message '${c}'`);}Ae(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=pa.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Hb(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Hb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Hb(f,!1,""+h)}):this.Hb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Hb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.va.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}De(a){const c=a.responseId,d=a.isOk;a=a.result;const e=qa.get(c);d?e.resolve(a):e.reject(a);qa.delete(c)}C(a,
c,d){let e=pa.get(a);e||(e=new Map,pa.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Ab(a){if(G.includes(a))throw Error("DOM handler already added");G.push(a)}hd(){for(const a of this.Nb)if("runtime"===a.ib){this.wa=a;return}throw Error("cannot find runtime DOM handler");}Be(a){this.Eb("debugger","message",a)}Ee(){for(const a of this.Nb)a.Yc()}static cb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
ua)}static nd(a){ua=!!a}gd(a){this.Va.push(a);this.zc()}Ge(a){a=this.Va.indexOf(a);if(-1===a)throw Error("invalid callback");this.Va.splice(a,1);this.Va.length||this.sc()}zc(){-1===this.Wa&&this.Va.length&&(this.Wa=requestAnimationFrame(this.Oe))}sc(){-1!==this.Wa&&(cancelAnimationFrame(this.Wa),this.Wa=-1)}Ce(){this.Wa=-1;for(const a of this.Va)a();this.zc()}Ba(a){this.wa.Ba(a)}Ja(a){this.wa.Ja(a)}yc(){this.wa.yc()}Gb(a){this.wa.Gb(a)}je(){return!!ka["audio/webm; codecs=opus"]}async Ie(a){a=await this.fd("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}ne(a){this.Kc=!0;this.vd=a}he(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}ed(a){return!this.he(a)}async La(a){return"cordova"===this.B&&(a.startsWith("file:")||this.Qb&&this.ed(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Bb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async ye(a){const c=a.filename;switch(a.as){case "text":return await this.fe(c);
case "buffer":return await this.Bb(c);default:throw Error("unsupported type");}}ad(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async fe(a){a=await this.ad(a);return await la(a)}tc(){if(E.length&&!(8<=F)){F++;var a=E.shift();this.se(a.filename,a.Ye,a.Re)}}Bb(a){return new Promise((c,d)=>{E.push({filename:a,Ye:e=>{F--;this.tc();c(e)},Re:e=>{F--;this.tc();d(e)}});this.tc()})}async se(a,c,d){try{const e=
await this.ad(a),f=await ma(e);c(f)}catch(e){d(e)}}He(){var a={type:"ready"};if("windows-webview2"===this.B)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.B)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async re(){const a=[];for(const [c,d]of Object.entries(this.qa))a.push(this.qe(c,d));await Promise.all(a)}async qe(a,c){if("object"===typeof c)this.qa[a]=new Blob([c.str],{type:c.type}),
this.Tb[a]=c.str;else{let d=await this.ue(c);d||(d=this.te(c));this.qa[a]=d}}async ue(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}te(a){a=this.Fe(a);return this.pe(a.data,a.Ue)}Fe(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+
1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Ue:a,data:d}}pe(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const H=self.fb;
function za(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const Aa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ba={dispatchUserScriptEvent:!0},Ca={dispatchRuntimeEvent:!0};
function Da(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ea(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function J(b){b=URL.createObjectURL(b);try{return await Ea(b)}finally{URL.revokeObjectURL(b)}}
function Fa(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ga(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await J(b);var d=await Fa(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await J(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await J(b)}
function Ha(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ia=new Set(["input","textarea","datalist","select"]),Ja=new Set(["canvas","body","html"]);function K(b){b.target.tagName&&Ja.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ka(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await J(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ga(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let La=!1;document.addEventListener("pause",()=>La=!0);document.addEventListener("resume",()=>La=!1);function xa(b){b.ud=!0;b.Oc=b.v.oa();b.pb=b.v.ia()}async function Ma(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Na(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Oa(b){return await self.C3_GetSvgImageSize(b.blob)}function Pa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Qa(b){self.setTimeout(()=>{b.td=!0},1E3);"cordova"===b.v.B?(document.addEventListener("pause",()=>Ra(b,!0)),document.addEventListener("resume",()=>Ra(b,!1))):document.addEventListener("visibilitychange",()=>Ra(b,document.hidden));return{isSuspended:!(!document.hidden&&!La)}}
function Sa(b){b.pd||(b.pd=!0,window.addEventListener("deviceorientation",a=>{b.Z||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.Z||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Ta(b){b.od||(b.od=!0,window.addEventListener("devicemotion",a=>{if(!b.Z){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Ua(b){await Da(b.url)}
function Va(b,a){b.wd=a.message;-1===b.Ec&&(b.Ec=setTimeout(()=>{b.Ec=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.wd)},250))}function L(b){if(!b.Z){var a=H.cb();a&&"any"!==b.Tc&&Wa(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ia()})}}function Xa(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:H.cb(),innerWidth:b.oa(),innerHeight:b.ia()})}
function Ra(b,a){a?b.v.sc():b.v.zc();k(b,"visibilitychange",{hidden:a})}function Ya(b,a,c){"Backspace"===c.key&&K(c);if(!b.Z){var d=Aa.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I)}}
function Za(b,a,c,d){b.Z||za(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function ab(b){window!==window.top&&window.focus();bb(b.target)&&document.activeElement&&!bb(document.activeElement)&&document.activeElement.blur()}
function M(b,a,c){if(!b.Z){var d=0;"mouse"===c.pointerType&&(d=b.ub);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},I);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Za(b,d,c,Ba),b.ub=c.buttons)}}
function cb(b,a,c){if(!b.Z&&!za(c)){var d=b.ub;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},I);b.ub=c.buttons;Za(b,c.type,c,Ba)}}
function N(b,a,c){if(!b.Z)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
I)}}function db(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function eb(b,a,c,d){const e=b.oa(),f=b.ia();b.Ya=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.cb()}):10>d&&gb(b,e,f,d+1)}
function gb(b,a,c,d){-1!==b.Ya&&clearTimeout(b.Ya);b.Ya=setTimeout(()=>eb(b,a,c,d),48)}
function Wa(b){b=b.Tc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function bb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.Ab(class extends self.Cb{constructor(b){super(b,"runtime");this.Bd=!0;this.ud=!1;this.Ya=-1;this.Tc="any";this.od=this.pd=!1;this.bc=document.createElement("div");this.bc.className="c3-screen-reader-text";this.bc.setAttribute("aria-live","polite");document.body.appendChild(this.bc);this.Ea=null;this.Z=!1;this.wd="";this.Ec=-1;this.td=!1;this.Oc=b.oa();this.pb=b.ia();this.da=this.yb=0;b.C("canvas","update-size",d=>{var e=this.v;e.Kc||(e=e.J,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+
"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Bd&&(e.style.display="",this.Bd=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Ma(d));b.C("runtime","raster-svg-image",d=>Na(d));b.C("runtime","get-svg-image-size",
d=>Oa(d));b.C("runtime","set-target-orientation",d=>{this.Tc=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Pa(d));b.C("runtime","go-to-script",d=>Pa(d));b.C("runtime","before-start-ticking",()=>Qa(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ea||(this.Ea=document.createElement("div"),this.Ea.id="inspectOutline",document.body.appendChild(this.Ea));var e=this.Ea;e.style.display="";e.style.left=
d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ea&&(this.Ea.style.display="none")});b.C("runtime","enable-device-orientation",()=>Sa(this));b.C("runtime","enable-device-motion",()=>Ta(this));b.C("runtime","add-stylesheet",d=>Ua(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>{alert(d.message)});
b.C("runtime","screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.bc.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.Z=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.J.style.display="";this.v.ne(d.duration)});b.C("runtime","export-to-video-progress",d=>Va(this,d));b.C("runtime","exported-to-video",d=>{window.Pe({type:"exported-video",
blob:d.blob,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.Pe({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ha(e)||d.preventDefault()});const c=b.J;window.addEventListener("selectstart",K);window.addEventListener("gesturehold",K);c.addEventListener("selectstart",K);c.addEventListener("gesturehold",K);window.addEventListener("touchstart",
K,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",K,{passive:!1}),c.addEventListener("pointerdown",K)):c.addEventListener("touchstart",K);this.ub=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ka,{passive:!1});window.addEventListener("wheel",Ka,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.Z&&this.ud){var d=this.oa();var e=this.ia();if(this.v.dd()){if(this.td){if(this.Oc===d&&
e<this.pb){this.yb=this.pb-e;db(this,this.pb,this.yb);d=void 0;break a}0<this.yb&&(this.yb=0,db(this,e,this.yb))}this.Oc=d;this.pb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.cb()});this.v.nc()&&(-1!==this.Ya&&clearTimeout(this.Ya),eb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>L(this));window.addEventListener("webkitfullscreenchange",()=>L(this));window.addEventListener("mozfullscreenchange",()=>
L(this));window.addEventListener("fullscreenerror",d=>Xa(this,d));window.addEventListener("webkitfullscreenerror",d=>Xa(this,d));window.addEventListener("mozfullscreenerror",d=>Xa(this,d));if(b.nc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ha(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(H.nd(!0),L(this)):"exited-fullscreen"===d?(H.nd(!1),L(this)):console.warn("Unknown wrapper message: ",d)};this.Ra=new Set;this.Vb=new WeakSet;this.ua=!1}Yc(){window.addEventListener("focus",()=>{k(this,"window-focus",null,Ca)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}k(this,"window-blur",{parentHasFocus:a},Ca);this.ub=0});window.addEventListener("focusin",a=>{a=a.target;(Ia.has(a.tagName.toLowerCase())||Ha(a))&&k(this,"keyboard-blur",null,Ca)});window.addEventListener("keydown",a=>Ya(this,"keydown",a));window.addEventListener("keyup",a=>Ya(this,"keyup",a));window.addEventListener("dblclick",a=>Za(this,"dblclick",a,I));window.addEventListener("wheel",a=>{this.Z||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,
deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{ab(a);M(this,"pointerdown",a)}),this.v.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{M(this,"pointermove",a)}):window.addEventListener("pointermove",a=>M(this,"pointermove",a)),window.addEventListener("pointerup",a=>M(this,"pointerup",a)),window.addEventListener("pointercancel",
a=>M(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{ab(a);cb(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>cb(this,"pointermove",a)),window.addEventListener("mouseup",a=>cb(this,"pointerup",a)),window.addEventListener("touchstart",a=>{ab(a);N(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>N(this,"pointermove",a)),window.addEventListener("touchend",a=>N(this,"pointerup",a)),window.addEventListener("touchcancel",a=>N(this,"pointercancel",a)));const b=
()=>this.yc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.ie()&&!this.v.dd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{db(this,this.ia(),navigator.virtualKeyboard.boundingRect.height)}))}oa(){return this.v.oa()}ia(){return this.v.ia()}yc(){var b=
[...this.Ra];this.Ra.clear();if(!this.ua)for(const a of b)(b=a.play())&&b.catch(()=>{this.Vb.has(a)||this.Ra.add(a)})}Ba(b){if("function"!==typeof b.play)throw Error("missing play function");this.Vb.delete(b);let a;try{a=b.play()}catch(c){this.Ra.add(b);return}a&&a.catch(()=>{this.Vb.has(b)||this.Ra.add(b)})}Ja(b){this.Ra.delete(b);this.Vb.add(b)}Gb(b){this.ua=!!b}});"use strict";
async function va(b){if(b.Je)throw Error("already initialised");b.Je=!0;var a=b.xa.uc(("playable-ad"===b.xa.B?b.xa.Xa:"")+"dispatchworker.js");b.Cc=await b.xa.ic(a,b.hb,{name:"DispatchWorker"});a=new MessageChannel;b.Jc=a.port1;b.Cc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Rc=await ya(b)}function wa(b){return[b.Jc,b.Rc]}
async function ya(b){const a=b.Cd.length;var c=b.xa.uc(("playable-ad"===b.xa.B?b.xa.Xa:"")+"jobworker.js");c=await b.xa.ic(c,b.hb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Cc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Cd.push(c);return e.port1}
self.le=class{constructor(b){this.xa=b;this.hb=b.ba;this.hb="preview"===b.B?this.hb+"workers/":this.hb+b.Xa;this.Le=Math.min(navigator.hardwareConcurrency||2,16);this.Cc=null;this.Cd=[];this.Rc=this.Jc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.fb({Ze:!0,$e:"workermain.js",Za:["scripts/c3runtime.js"],ec:[],Wc:"",We:"scripts/",fc:[],Pd:"html5"}));"use strict";
async function hb(b,a){a=a.type;let c=!0;0===a?c=await ib():1===a&&(c=await jb());k(b,"permission-result",{type:a,result:c})}async function ib(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function jb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.fb.Ab(class extends self.Cb{constructor(b){super(b,"touch");p(this,"request-permission",a=>hb(this,a))}});"use strict";const kb=180/Math.PI;
async function lb(b,a){if(a.isiOSCordova||a.isSafari)b.Yb=!0;b.Uc=a.timeScaleMode;b.Hd=["equalpower","HRTF","soundfield"][a.panningModel];b.sd=["linear","inverse","exponential"][a.distanceModel];b.Id=a.refDistance;b.Gd=a.maxDistance;b.Kd=a.rolloffFactor;if(b.v.Kc)b.Yb=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.vd)});else{var c={latencyHint:a.latencyHint};b.Nd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");mb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&mb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Na=b.g.createGain();b.Na.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ea);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
O(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function nb(b,a){var c=a.originalUrl;const d=a.url,e=a.type,f=a.isMusic,g=a.tag,h=a.isLooping,m=a.vol,q=a.pos,n=a.panning,A=a.stereoPan;let x=a.off;0<x&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+b.g.currentTime);b.Dd=g;ob(b,g);try{b.$=await pb(b,c,d,e,g,f);if(n){P(b.$,!0);var r=b.$,B=n.innerAngle,na=n.outerAngle,oa=n.outerGain;if(r.nb){qb(r,n.x,n.y,n.z,n.angle);var D=self.$a.oe;r.ra[0]!==D(B)&&(r.ra[0]=
D(B),r.F.coneInnerAngle=D(B));r.ra[1]!==D(na)&&(r.ra[1]=D(na),r.F.coneOuterAngle=D(na));r.ra[2]!==oa&&(r.ra[2]=oa,r.F.coneOuterGain=oa)}n.hasOwnProperty("uid")&&(b.$.pa=n.uid)}else"number"===typeof A&&0!==A?(Q(b.$,!0),rb(b.$,A)):(P(b.$,!1),Q(b.$,!1));b.$.Play(h,m,q,x)}catch(Db){console.error("[Construct] Audio: error starting playback: ",Db);return}finally{c=b.wb.get(g);if(!c)throw Error("expected pending tag");c.Xc--;0===c.Xc&&(c.resolve(),b.wb.delete(g))}t(b)}
async function sb(b,a){var c=a.tag;const d=a.vol,e=a.duration;a=a.stopOnEnd;await tb(b,c);for(const n of R(b,c)){c=n;var f=d,g=e,h=a;if(!c.Pa){var m=c.G.gain;m.cancelScheduledValues(0);var q=c.s.g.currentTime;g=q+g;m.setValueAtTime(m.value,q);m.linearRampToValueAtTime(f,g);c.Ha=f;c.Oa=g;c.Md=h}}S(b)}async function ub(b,a){const c=a.tag;a=a.rate;await tb(b,c);for(const d of R(b,c))b=d,b.ma!==a&&(b.ma=a,b.Ca())}
async function vb(b,a){const c=a.tag;a=a.pos;await tb(b,c);for(const d of R(b,c))d.oc(a)}async function wb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await pb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function xb(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ka.indexOf(a),-1!==a&&b.ka.splice(a,1)}
async function yb(b,a){var c=a.type,d=a.tag,e=a.params;if("filter"===c)e=new self.Vd(b,...e);else if("delay"===c)e=new self.Td(b,...e);else if("convolution"===c){c=null;try{c=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(g){console.log("[Construct] Audio: error loading convolution: ",g);return}c=e=new self.Sd(b,c.ja,...e);var f=a.bufferType;c.qd=a.bufferOriginalUrl;c.rd=f}else if("flanger"===c)e=new self.Wd(b,...e);else if("phaser"===c)e=new self.Yd(b,...e);else if("gain"===c)e=
new self.Xd(b,...e);else if("stereopan"===c)e=new self.$d(b,...e);else if("tremolo"===c)e=new self.ae(b,...e);else if("ringmod"===c)e=new self.Zd(b,...e);else if("distortion"===c)e=new self.Ud(b,...e);else if("compressor"===c)e=new self.Rd(b,...e);else if("analyser"===c)e=new self.Qd(b,...e);else throw Error("invalid effect type");a=e;d=d.toLowerCase();e=b.la.get(d);e||(e=[],b.la.set(d,e));a.Ad=e.length;a.ga=d;e.push(a);zb(b,d);Ab(b)}
async function Bb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.I)e.za()&&1===c||!e.za()&&2===c?d.push(e):e.j();b.I=d}for(const f of b.la.values())for(const g of f)g.j();b.la.clear();b.cc=a.timeScale;b.Fc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ea[e]=d[e];b.g.listener.setOrientation(...b.ea)}b.ua=a.isSilent;b.v.Gb(b.ua);b.Ub=a.masterVolume;b.Na.gain.value=
b.Ub;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>yb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Eb(b,f,c)));S(b)}
async function Fb(b,a){try{const c=b.g.suspend(a.time);b.zd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.Eb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Gb(d)),b.zd=!0);await c}catch(c){Gb(c)}}
function mb(b){b.Ob||(b.Ic=!1,window.addEventListener("pointerup",b.ya,!0),window.addEventListener("touchend",b.ya,!0),window.addEventListener("click",b.ya,!0),window.addEventListener("keydown",b.ya,!0),b.Ob=!0)}
async function O(b,a,c,d,e,f){for(var g of b.ka)if(g.bb()===c)return await Hb(g),g;if(f)return null;if(e&&(b.Yb||b.yd)){f=0;for(let h=0,m=b.ka.length;h<m;++h)g=b.ka[h],b.ka[f]=g,g.za()?g.j():++f;b.ka.length=f}f="audio/webm; codecs=opus"===d&&!b.Nd;e&&f&&(b.yd=!0);c=!e||b.Yb||f?new self.de(b,a,c,d,e,f):new self.be(b,a,c,d,e);b.ka.push(c);await Hb(c);b.Fd.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ha()}),b.Fd.add(a));return c}
function Ib(b,a){return(a=b.la.get(a.toLowerCase()))?a[0].N():b.na()}function zb(b,a){let c=b.na();var d=b.la.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.S(b.na()):e.S(d[f+1].N())}}for(const f of R(b,a))d=c,e=f.fa||f.F||f.G,e.disconnect(),e.connect(d);b.Fa&&b.Pc===a&&(b.Fa.disconnect(),b.Fa.connect(c))}
function*R(b,a){if(a)for(const c of b.I)b=c.ga,(b.length!==a.length?0:b===a||b.toLowerCase()===a.toLowerCase())&&(yield c);else b.$&&!b.$.U()&&(yield b.$)}function Jb(b,a,c){return c?b.v.Ie(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Kb(b,a){let c=0;for(let d=0,e=b.I.length;d<e;++d){const f=b.I[d];b.I[c]=f;f.O===a?f.j():++c}b.I.length=c}
async function pb(b,a,c,d,e,f){for(const g of b.I)if(g.bb()===c&&(g.hc()||f))return g.ga=e,g;a=await O(b,a,c,d,f);e="html5"===a.Ac?new self.ce(a.s,a,e):new self.ee(a.s,a,e);b.I.push(e);return e}function ob(b,a){let c=b.wb.get(a);if(!c){let d=null;c={Xc:0,promise:new Promise(e=>d=e),resolve:d};b.wb.set(a,c)}c.Xc++}function tb(b,a){a||(a=b.Dd);return(b=b.wb.get(a))?b.promise:Promise.resolve()}function S(b){if(0<b.Ma.size)t(b);else for(const a of b.I)if(!a.H&&!a.U()){t(b);break}}
function Lb(b,a,c,d){k(b,"trigger",{type:a,tag:c,aiid:d})}function Ab(b){b.Lc||(b.Lc=!0,Promise.resolve().then(()=>Mb(b)))}function Mb(b){const a={};for(const [c,d]of b.la)a[c]=d.map(e=>e.ab());k(b,"fxstate",{fxstate:a});b.Lc=!1}
async function Eb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tag,m=a.isLooping,q=a.volume,n=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await pb(b,d,e,f,h,g)}catch(A){console.error("[Construct] Audio: error loading audio state: ",A);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.Ta[0]=f[0],b.Ta[1]=f[1],b.Ta[2]=f[2],f=d.orient,b.Sa[0]=f[0],b.Sa[1]=f[1],b.Sa[2]=f[2],e.setPosition(...b.Ta),e.setOrientation(...b.Sa),b.ra[0]=d.cia,b.ra[1]=d.coa,b.ra[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.pa=d.uid):P(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?Q(b,!1):(Q(b,!0),rb(b,d));c.Play(m,q,n,0);a.isPlaying||c.eb();c.wc(a)}}}function Gb(b){console.error("[Audio] Offline rendering error: ",b)}
self.$a=class extends self.Cb{constructor(b){super(b,"audio");this.Na=this.g=null;this.Ob=this.Ic=!1;this.ya=()=>{if(!this.Ic){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Ob&&(this.Ic=!0,window.removeEventListener("pointerup",this.ya,!0),window.removeEventListener("touchend",this.ya,!0),window.removeEventListener("click",this.ya,!0),window.removeEventListener("keydown",
this.ya,!0),this.Ob=!1)}};this.ka=[];this.I=[];this.$=null;this.Dd="";this.Fd=new Set;this.Ed=-1;this.wb=new Map;this.Ub=1;this.ua=!1;this.Uc=0;this.cc=1;this.Fc=0;this.Hd="HRTF";this.sd="inverse";this.Id=600;this.Gd=1E4;this.Kd=1;this.aa=[0,0,0];this.ea=[0,0,-1,0,1,0];this.yd=this.Yb=!1;this.Nd=this.v.je();this.la=new Map;this.Ma=new Set;this.zd=this.Lc=!1;this.Pc="";this.Fa=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Fa&&this.Fa.disconnect();this.Pc=c.toLowerCase();this.Fa=this.g.createMediaStreamSource(a);
this.Fa.connect(Ib(this,this.Pc))};this.Mb=null;self.C3Audio_GetOutputStream=()=>{this.Mb||(this.Mb=this.g.createMediaStreamDestination(),this.Na.connect(this.Mb));return this.Mb.stream};self.C3Audio_DOMInterface=this;aa(this,[["create-audio-context",a=>lb(this,a)],["play",a=>nb(this,a)],["stop",a=>{a=a.tag;for(const c of R(this,a))c.Aa()}],["stop-all",()=>{for(const a of this.I)a.Aa()}],["set-paused",a=>{const c=a.tag;a=a.paused;for(const d of R(this,c))a?d.eb():d.Fb();S(this)}],["set-volume",a=>
{const c=a.tag;a=a.vol;for(const d of R(this,c))T(d,a)}],["fade-volume",a=>sb(this,a)],["set-master-volume",a=>{this.Ub=a.vol;this.Na.gain.value=this.Ub}],["set-muted",a=>{const c=a.tag;a=a.isMuted;for(const d of R(this,c))Nb(d,a)}],["set-silent",a=>{this.ua=a.isSilent;this.v.Gb(this.ua);for(const c of this.I)c.Jb()}],["set-looping",a=>{const c=a.tag;a=a.isLooping;for(const d of R(this,c))d.pc(a)}],["set-playback-rate",a=>ub(this,a)],["set-stereo-pan",a=>{const c=a.tag;a=a.p;for(const d of R(this,
c))Q(d,!0),rb(d,a)}],["seek",a=>vb(this,a)],["preload",a=>wb(this,a)],["unload",a=>xb(this,a)],["unload-all",()=>{for(const a of this.ka)a.j();this.ka.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.I)c.qc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>yb(this,a)],["set-effect-param",a=>{const c=a.index,d=a.param,e=a.value,f=a.ramp,g=a.time;a=this.la.get(a.tag);!a||0>c||c>=a.length||(a[c].Y(d,e,f,g),Ab(this))}],["remove-effects",a=>
{a=a.tag.toLowerCase();const c=this.la.get(a);if(c&&c.length){for(const d of c)d.j();this.la.delete(a);zb(this,a)}}],["tick",a=>{this.cc=a.timeScale;this.Fc=a.gameTime;this.Ed=a.tickCount;if(0!==this.Uc)for(var c of this.I)c.Ca();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ea[0]!==c[0]||this.ea[1]!==c[1]||this.ea[2]!==c[2]||this.ea[3]!==
c[3]||this.ea[4]!==c[4]||this.ea[5]!==c[5])){for(let d=0;6>d;++d)this.ea[d]=c[d];this.g.listener.setOrientation(...this.ea)}for(const d of a.instPans){a=d.uid;for(const e of this.I)e.pa===a&&qb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Bb(this,a)],["offline-render-audio",a=>Fb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}na(){return this.Na}Db(){return this.ua}Ba(b){this.v.Ba(b)}Ja(b){this.v.Ja(b)}Ka(){for(var b of this.Ma)b.Ka();b=this.g.currentTime;for(var a of this.I)a.Ka(b);
a=this.I.filter(c=>!c.H&&!c.U()).map(c=>c.ab());k(this,"state",{tickCount:this.Ed,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ma].map(c=>({tag:c.ga,index:c.Ad,peak:c.Ua,rms:c.Jd,binCount:c.l.frequencyBinCount,freqBins:c.xd}))});0===a.length&&0===this.Ma.size&&this.Pb&&(this.v.Ge(this.Od),this.Pb=!1)}static oe(b){return b*kb}static cd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static me(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*20}};self.fb.Ab(self.$a);
"use strict";function Hb(b){b.Sb||(b.Sb=b.vc());return b.Sb}self.Zc=class{constructor(b,a,c,d,e){this.s=b;this.Ne=a;this.Ga=c;this.R=d;this.Ke=e;this.Ac="";this.Sb=null}j(){this.Sb=this.s=null}vc(){}V(){return this.s.V()}kc(){return this.Ne}bb(){return this.Ga}jc(){return this.R}za(){return this.Ke}ha(){}};"use strict";
self.be=class extends self.Zc{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Ac="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.qb=this.rb=null;this.M.addEventListener("canplaythrough",()=>!0);this.vb=this.V().createGain();this.tb=null;this.M.addEventListener("canplay",()=>{this.rb&&(this.rb(),this.qb=this.rb=null);!this.tb&&this.M&&(this.tb=this.V().createMediaElementSource(this.M),this.tb.connect(this.vb))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ga}' error: `,f);this.qb&&(this.qb(f),this.qb=this.rb=null)})}j(){Kb(this.s,this);this.vb.disconnect();this.vb=null;this.tb.disconnect();this.tb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}vc(){return new Promise((b,a)=>{this.rb=b;this.qb=a;this.M.src=this.Ga})}T(){return this.M}ha(){return this.M.duration}};"use strict";
async function Ob(b){if(b.Da)return b.Da;var a=b.s.v;if("cordova"===a.B&&a.ed(b.Ga)&&a.Qb)b.Da=await a.Bb(b.Ga);else{a=await fetch(b.Ga);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Da=await a.arrayBuffer()}}async function Pb(b){if(b.ja)return b.ja;b.ja=await Jb(b.s,b.Da,b.Me);b.Da=null}
self.de=class extends self.Zc{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Ac="webaudio";this.ja=this.Da=null;this.Me=!!f}j(){Kb(this.s,this);this.ja=this.Da=null;super.j()}async vc(){try{await Ob(this),await Pb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ga}': `,b)}}ha(){return this.ja?this.ja.duration:0}};"use strict";let Qb=0;
function P(b,a){a=!!a;b.nb!==a&&(b.nb=a,b.nb?(Q(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.s.Hd,b.F.distanceModel=b.s.sd,b.F.refDistance=b.s.Id,b.F.maxDistance=b.s.Gd,b.F.rolloffFactor=b.s.Kd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.na())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.na())))}
function Q(b,a){a=!!a;b.Rb!==a&&(b.Rb=a,b.Rb?(P(b,!1),b.fa=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.fa),b.fa.connect(b.na())):(b.fa.disconnect(),b.fa=null,b.G.disconnect(),b.G.connect(b.na())))}function rb(b,a){b.Rb&&b.Sc!==a&&(b.fa.pan.value=a,b.Sc=a)}function T(b,a){b.Ha=a;b.G.gain.cancelScheduledValues(0);b.Oa=-1;b.G.gain.value=b.lc()}function Nb(b,a){a=!!a;b.Pa!==a&&(b.Pa=a,b.Jb())}
function qb(b,a,c,d,e){if(b.nb){var f=b.Ta,g=b.Sa,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.Mc?b.s.Fc:performance.now()/1E3}
self.$c=class{constructor(b,a,c){this.s=b;this.O=a;this.ga=c;this.Kb=Qb++;this.G=this.V().createGain();this.G.connect(this.na());this.F=null;this.nb=!1;this.Ta=[0,0,0];this.Sa=[0,0,0];this.ra=[0,0,0];this.fa=null;this.Rb=!1;this.Sc=0;this.H=!0;this.X=this.sa=this.K=!1;this.Ha=1;this.Pa=!1;this.ma=1;b=this.s.Uc;this.Mc=1===b&&!this.za()||2===b;this.Oa=this.pa=-1;this.Md=!1}j(){this.O=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.fa&&(this.fa.disconnect(),this.fa=null);this.G.disconnect();
this.G=null}V(){return this.s.V()}na(){return Ib(this.s,this.ga)}kc(){return this.O.kc()}bb(){return this.O.bb()}jc(){return this.O.jc()}za(){return this.O.za()}U(){}hc(){}IsPlaying(){return!this.H&&!this.K&&!this.U()}Ia(){}ha(){return this.O.ha()}Play(){}Aa(){}eb(){}Fb(){}Ka(b){-1!==this.Oa&&b>=this.Oa&&(this.Oa=-1,this.Md&&this.Aa(),Lb(this.s,"fade-ended",this.ga,this.Kb))}lc(){const b=this.Ha;return isFinite(b)?b:0}Db(){return this.s.Db()}Jb(){}pc(){}Ca(){}oc(){}qc(){}mc(){}ab(){var b=this.Kb,
a=this.ga,c=this.ha(),d=-1===this.Oa?this.Ha:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ta,orient:this.Sa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.pa}}else f=null;return{aiid:b,tag:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ia(),playbackRate:this.ma,uid:this.pa,bufferOriginalUrl:this.kc(),bufferUrl:"",bufferType:this.jc(),isMusic:this.za(),isLooping:this.X,isMuted:this.Pa,resumePosition:this.mc(),pan:f,stereoPan:this.fa?this.Sc:
null}}wc(b){var a=b.playbackRate;this.ma!==a&&(this.ma=a,this.Ca());Nb(this,b.isMuted)}};"use strict";
self.ce=class extends self.$c{constructor(b,a,c){super(b,a,c);this.O.vb.connect(this.G);this.O.onended=()=>this.xc()}j(){this.Aa();this.O.vb.disconnect();super.j()}T(){return this.O.T()}xc(){this.H=!0;this.pa=-1;Lb(this.s,"ended",this.ga,this.Kb)}U(){return this.T().ended}hc(){return this.H?!0:this.U()}Ia(){let b=this.T().currentTime;this.X||(b=Math.min(b,this.ha()));return b}Play(b,a,c){const d=this.T();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.O.bb()}' to position '${c}': `,e)}this.s.Ba(d);this.K=this.H=!1;this.X=b;this.ma=1}Aa(){const b=this.T();b.paused||b.pause();this.s.Ja(b);this.H=!0;this.K=!1;this.pa=-1}eb(){if(!(this.K||this.H||this.U())){var b=this.T();b.paused||b.pause();this.s.Ja(b);this.K=!0}}Fb(){!this.K||this.H||this.U()||(this.s.Ba(this.T()),this.K=!1)}Jb(){this.T().muted=this.Pa||this.Db()}pc(b){b=!!b;this.X!==b&&(this.X=
b,this.T().loop=b)}Ca(){let b=this.ma;this.Mc&&(b*=this.s.cc);try{this.T().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}oc(b){if(!this.H&&!this.U())try{this.T().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}mc(){return this.Ia()}qc(b){b?this.IsPlaying()?(this.T().pause(),this.sa=!0):this.sa=!1:this.sa&&(this.s.Ba(this.T()),this.sa=!1)}};"use strict";function V(b){b.o&&b.o.disconnect();b.o=null;b.gb=null}
self.ee=class extends self.$c{constructor(b,a,c){super(b,a,c);this.o=null;this.Wb=d=>this.xc(d);this.Hc=!0;this.gb=null;this.P=this.Xb=this.Zb=0;this.Qc=1}j(){this.Aa();V(this);this.Wb=null;super.j()}xc(b){this.K||this.sa||b.target!==this.gb||(this.H=this.Hc=!0,this.pa=-1,V(this),Lb(this.s,"ended",this.ga,this.Kb))}U(){return!this.H&&this.o&&this.o.loop||this.K?!1:this.Hc}hc(){return!this.o||this.H?!0:this.U()}Ia(){let b;b=this.K?this.P:this.Xb+(U(this)-this.Zb)*this.ma;this.X||(b=Math.min(b,this.ha()));
return b}Play(b,a,c,d){this.Qc=1;T(this,a);V(this);this.o=this.V().createBufferSource();this.o.buffer=this.O.ja;this.o.connect(this.G);this.gb=this.o;this.o.onended=this.Wb;this.o.loop=b;this.o.start(d,c);this.K=this.H=this.Hc=!1;this.X=b;this.ma=1;this.Zb=U(this);this.Xb=c}Aa(){if(this.o)try{this.o.stop(0)}catch(b){}this.H=!0;this.K=!1;this.pa=-1}eb(){this.K||this.H||this.U()||(this.P=this.Ia(),this.X&&(this.P%=this.ha()),this.K=!0,this.o.stop(0))}Fb(){!this.K||this.H||this.U()||(V(this),this.o=
this.V().createBufferSource(),this.o.buffer=this.O.ja,this.o.connect(this.G),this.gb=this.o,this.o.onended=this.Wb,this.o.loop=this.X,T(this,this.Ha),this.Ca(),this.o.start(0,this.P),this.Zb=U(this),this.Xb=this.P,this.K=!1)}lc(){return super.lc()*this.Qc}Jb(){this.Qc=this.Pa||this.Db()?0:1;T(this,this.Ha)}pc(b){b=!!b;this.X!==b&&(this.X=b,this.o&&(this.o.loop=b))}Ca(){let b=this.ma;this.Mc&&(b*=this.s.cc);this.o&&(this.o.playbackRate.value=b)}oc(b){this.H||this.U()||(this.K?this.P=b:(this.eb(),this.P=
b,this.Fb()))}mc(){return this.P}qc(b){b?this.IsPlaying()?(this.sa=!0,this.P=this.Ia(),this.X&&(this.P%=this.ha()),this.o.stop(0)):this.sa=!1:this.sa&&(V(this),this.o=this.V().createBufferSource(),this.o.buffer=this.O.ja,this.o.connect(this.G),this.gb=this.o,this.o.onended=this.Wb,this.o.loop=this.X,T(this,this.Ha),this.Ca(),this.o.start(0,this.P),this.Zb=U(this),this.Xb=this.P,this.sa=!1)}wc(b){super.wc(b);this.P=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Y{constructor(b){this.s=b;this.g=b.V();this.Ad=-1;this.R=this.ga="";this.m=null}j(){this.g=null}N(){}S(){}ab(){return{type:this.R,tag:this.ga,params:this.m}}}
self.Vd=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.R="filter";this.m=[a,c,d,e,f,g];this.u=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i)}j(){this.u.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;X(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;X(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,X(this,this.D.gain,a,c,d)}}};
self.Td=class extends Y{constructor(b,a,c,d){super(b);this.R="delay";this.m=[a,c,d];this.u=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.sb=W(this);this.W=this.g.createDelay(a);this.W.delayTime.value=a;this.kb=W(this);this.kb.gain.value=c;this.u.connect(this.sb);this.u.connect(this.h);this.sb.connect(this.i);this.sb.connect(this.W);this.W.connect(this.kb);this.kb.connect(this.sb)}j(){this.u.disconnect();this.i.disconnect();this.h.disconnect();this.sb.disconnect();
this.W.disconnect();this.kb.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){const e=self.$a.cd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);X(this,this.kb.gain,e(a),c,d);break;case 5:this.m[0]=a,X(this,this.W.delayTime,a,c,d)}}};
self.Sd=class extends Y{constructor(b,a,c,d){super(b);this.R="convolution";this.m=[c,d];this.rd=this.qd="";this.u=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.jb=this.g.createConvolver();this.jb.normalize=c;this.jb.buffer=a;this.u.connect(this.jb);this.u.connect(this.h);this.jb.connect(this.i)}j(){this.u.disconnect();this.jb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}ab(){const b=super.ab();b.bufferOriginalUrl=this.qd;b.bufferUrl="";b.bufferType=this.rd;return b}};
self.Wd=class extends Y{constructor(b,a,c,d,e,f){super(b);this.R="flanger";this.m=[a,c,d,e,f];this.u=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.mb=W(this);this.mb.gain.value=e;this.W=this.g.createDelay(a+c);this.W.delayTime.value=a;this.A=this.g.createOscillator();this.A.frequency.value=d;this.L=W(this);this.L.gain.value=c;this.u.connect(this.W);this.u.connect(this.h);this.W.connect(this.i);this.W.connect(this.mb);this.mb.connect(this.W);this.A.connect(this.L);
this.L.connect(this.W.delayTime);this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.W.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.mb.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;X(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;X(this,this.A.frequency,a,c,d);break;case 8:this.m[3]=a/100,X(this,this.mb.gain,a/100,c,d)}}};
self.Yd=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.R="phaser";this.m=[a,c,d,e,f,g];this.u=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.A=this.g.createOscillator();this.A.frequency.value=f;this.L=W(this);this.L.gain.value=e;this.u.connect(this.D);this.u.connect(this.h);this.D.connect(this.i);this.A.connect(this.L);this.L.connect(this.D.frequency);
this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.D.disconnect();this.A.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;X(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;X(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;X(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,X(this,this.A.frequency,a,c,d)}}};self.Xd=class extends Y{constructor(b,a){super(b);this.R="gain";this.m=[a];this.l=W(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){const e=self.$a.cd;switch(b){case 4:this.m[0]=e(a),X(this,this.l.gain,e(a),c,d)}}};
self.$d=class extends Y{constructor(b,a){super(b);this.R="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,X(this,this.l.pan,a,c,d)}}};
self.ae=class extends Y{constructor(b,a,c){super(b);this.R="tremolo";this.m=[a,c];this.l=W(this);this.l.gain.value=1-c/2;this.A=this.g.createOscillator();this.A.frequency.value=a;this.L=W(this);this.L.gain.value=c/2;this.A.connect(this.L);this.L.connect(this.l.gain);this.A.start(0)}j(){this.A.stop(0);this.A.disconnect();this.L.disconnect();this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;X(this,this.l.gain,1-a/2,c,d);X(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,X(this,this.A.frequency,a,c,d)}}};
self.Zd=class extends Y{constructor(b,a,c){super(b);this.R="ringmod";this.m=[a,c];this.u=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.xb=W(this);this.xb.gain.value=0;this.A=this.g.createOscillator();this.A.frequency.value=a;this.A.connect(this.xb.gain);this.A.start(0);this.u.connect(this.xb);this.u.connect(this.h);this.xb.connect(this.i)}j(){this.A.stop(0);this.A.disconnect();this.xb.disconnect();this.u.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,X(this,this.A.frequency,a,c,d)}}};
self.Ud=class extends Y{constructor(b,a,c,d,e,f){super(b);this.R="distortion";this.m=[a,c,d,e,f];this.u=W(this);this.ac=W(this);this.$b=W(this);b=d;.01>b&&(b=.01);this.ac.gain.value=b;this.$b.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.dc=this.g.createWaveShaper();this.Bc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Bc[32768+e]=f,this.Bc[32768-
e-1]=-f;this.dc.curve=this.Bc;this.u.connect(this.ac);this.u.connect(this.h);this.ac.connect(this.dc);this.dc.connect(this.$b);this.$b.connect(this.i)}j(){this.u.disconnect();this.ac.disconnect();this.dc.disconnect();this.$b.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.u}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.Rd=class extends Y{constructor(b,a,c,d,e,f){super(b);this.R="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};
self.Qd=class extends Y{constructor(b,a,c){super(b);this.R="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.xd=new Float32Array(this.l.frequencyBinCount);this.Ld=new Uint8Array(a);this.Jd=this.Ua=0;b=this.s;b.Ma.add(this);S(b)}j(){this.s.Ma.delete(this);this.l.disconnect();super.j()}Ka(){this.l.getFloatFrequencyData(this.xd);this.l.getByteTimeDomainData(this.Ld);const b=this.l.fftSize;let a=this.Ua=0;for(var c=0;c<b;++c){let d=(this.Ld[c]-
128)/128;0>d&&(d=-d);this.Ua<d&&(this.Ua=d);a+=d*d}c=self.$a.me;this.Ua=c(this.Ua);this.Jd=c(Math.sqrt(a/b))}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};"use strict";function Z(b){b.stopPropagation()}
self.fb.Ab(class extends self.ge{constructor(b){super(b);v(this,"click",a=>{a.click()});v(this,"clear",a=>{a.value=""})}bd(b,a){const c=document.createElement("input");c.type="file";c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",Z);c.addEventListener("pointermove",Z);c.addEventListener("pointerrawupdate",Z);c.addEventListener("pointerup",Z);c.addEventListener("mousedown",Z);c.addEventListener("mouseup",Z);c.addEventListener("change",
()=>u(this,"change",b,{files:Array.from(c.files)}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.rc(c,a);return c}rc(b,a){b.setAttribute("accept",a.accept);a.isMultiSelect?b.setAttribute("multiple",""):b.removeAttribute("multiple")}});
